name: Using Context Var

#on: push
on: workflow_dispatch

jobs:
  prod-check:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Calling variable from environment dev
        run: echo ${{ vars.FROM_ENV_VAR }}
      - name: Calling secret from environment dev
        run: echo ${{ secrets.FROM_SECRET_VAR }}
