name: Hello world

# on: [push]
on:
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run step
        run: echo "Hello World"
