name: Multiple trigger

# on: [push]
# #on : [push, workflow_dispatch]
on:
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run step
        run: echo "Hello World"
