name: Cron

# on:
#   schedule:
#     # - cron: "0 16 * * *" 
#     - cron: "*/5 * * * *"

on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run at 12 AM every GMT+8 & every 2 minutes.
      run: echo "This job runs every Monday at 9 AM UTC+8"
